server:
  port: 8089
spring:
  application:
    name: wblog-backend
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wblog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ff514519
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:mapper/*.xml
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    key-id:
    key-secret:
    bucket-name: pictures01
qiniu:
  accessKey:
  accessSecretKey: 
